### ISSUE TITLE
EOC Portuguese Student Data

### ISSUE THREAD

**Issue by Theanalyst152** [mfenner1/mlwpy_code#2]
There's something wrong with the import for the student data. When you import, and use the student-numeric.csv it doesn't have the absence column just the x y values. This is the end of chapter 7 and 8. Please share correct code . According to your book it is suppose to keep numerical values and column G3. Your code only keeps two columns and I can't figure it out.
Thanks

**Comment by mfenner1** [comment]
For some reason, github didn't update me with these issues ... I'll look into this and get back to you.  Thank you for reporting the issue.

**Comment by mfenner1** [comment]
Digging into this, I updated all my packages and the net result is the following csv.  It appears to work as advertised.

```bash
% head portugese_student_numeric.csv 
age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G3
18,4,4,2,2,0,4,3,4,1,1,3,6,6
17,1,1,1,2,0,5,3,3,1,1,3,4,6
15,1,1,1,2,3,4,3,2,2,3,3,10,10
15,4,2,1,3,0,3,2,2,1,1,5,2,15
16,3,3,1,2,0,4,3,2,1,2,5,4,10
16,4,3,1,2,0,5,4,2,1,2,5,10,15
16,2,2,1,2,0,4,4,4,1,1,3,0,11
17,4,4,2,2,0,4,1,4,1,1,1,6,6
15,3,2,1,2,0,4,2,2,1,1,1,0,19
```
