### ISSUE TITLE
4.5.2 Learning Performance  (MSE) v 4.5.3 Resource Utilization in Regression

### ISSUE THREAD

**Issue by DavidAKZ** [mfenner1/mlwpy_code#9]
Don't we need the same data set to compare 'apples with apples' ? 4.5.2 measures Mean Square Error on the iris dataset. While 4.5.3 measures execution time and memory use for kin and linear regression on the diabetes data set.

**Comment by mfenner1** [comment]
The resource utilization in 4.5.3 should be pointed at diabetes, not at iris.  Not sure how that bug survived this long!  Good catch.  I'll have to push a fix for that.  Thank you.

**Comment by Henro911** [comment]
I'm confused 😕

**Comment by mfenner1** [comment]
I can't find this in the most recent 04_ notebook, so I'm closing this.  I'm assuming it is a typo in the book.
